title: Smartminions
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
base_font: nunito-sans
palette: orange
header:
  logo_img: images/logo-alt.png
  logo_img_alt: Logo
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Systems
      url: /systems
      style: link
    - label: Services
      url: /services
      style: link
    - label: Contact
      url: /contact
      style: primary
footer:
  sections:
    - type: footer_text
      image: images/smartminions-black-small.png
      image_url: /
      content: Your one-stop shop to home automation.
    - type: footer_nav
      title: Company
      nav_links:
        - label: About Us
          url: /about
          style: link
        # - label: Blog
          # url: /blog
          # style: link
        - label: Contact
          url: /contact
          style: link
    - type: footer_nav
      title: Social platform
      nav_links:
        - label: Facebook
          url: 'https://www.facebook.com/SmartMinionsAustralia'
          style: link
          has_icon: true
          icon: facebook
          icon_position: left
        - label: Wechat
          url: ''
          style: link
          has_icon: true
          icon: wechat
          icon_position: left
        # - label: LinkedIn
          # url: 'https://www.linkedin.com/'
          # style: link
          # has_icon: true
          # icon: linkedin
          # icon_position: left
        # - label: GitHub
          # url: 'https://github.com/'
          # style: link
          # has_icon: true
          # icon: github
          # icon_position: left
    # - type: footer_form
      # title: Subscribe
      # content: Stay up to date with our latest developments.
      # form_id: contactForm
      # hide_labels: true
      # form_fields:
        # - input_type: email
          # name: email
          # label: Email
          # default_value: Enter email address
          # is_required: true
      # submit_label: Subscribe
  has_nav: true
  nav_links:
    # - label: Terms of Service
      # url: /terms-of-service
      # style: link
    # - label: Privacy Policy
      # url: /privacy-policy
      # style: link
  content: >-
    &copy; Smartminions. All rights reserved. ABN 81 642 608 839. 8 Cape Street Dickson, ACT , 2602, Australia.
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
